# Generated by Django 3.0.5 on 2020-05-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0016_auto_20200505_1717'),
        ('posts', '0002_auto_20200505_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='account.User')),
                ('follows', models.ManyToManyField(blank=True, related_name='follows', to='account.User')),
                ('posts', models.ManyToManyField(blank=True, to='posts.Post')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
