# Generated by Django 3.0.5 on 2020-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='posts',
        ),
    ]
