# Generated by Django 3.0.5 on 2020-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200507_0127'),
        ('feeds', '0003_userfeeds_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='follows',
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to='account.User'),
        ),
    ]
