# Generated by Django 3.0.5 on 2020-05-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='content',
        ),
        migrations.CreateModel(
            name='Comment_chein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_chein_fk', to='posts.Comments')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_chein_fk', to='posts.Content')),
            ],
            options={
                'db_table': 'Comment_chein',
            },
        ),
        migrations.AlterField(
            model_name='content',
            name='comment',
            field=models.ManyToManyField(related_name='content_comment', through='posts.Comment_chein', to='posts.Comments'),
        ),
    ]
