# Generated by Django 3.0.5 on 2020-05-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200513_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='images',
        ),
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Content'),
        ),
        migrations.DeleteModel(
            name='Content_image',
        ),
    ]
