# Generated by Django 3.0.5 on 2020-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200505_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.TextField(blank=True, default=''),
        ),
    ]
