# Generated by Django 3.0.5 on 2020-05-16 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200513_1350'),
        ('posts', '0003_auto_20200516_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment',
            field=models.ManyToManyField(related_name='content_comment', through='posts.Comments', to='account.User'),
        ),
        migrations.AlterField(
            model_name='content',
            name='like',
            field=models.ManyToManyField(related_name='likes', through='posts.Like', to='account.User'),
        ),
        migrations.DeleteModel(
            name='Comment_chein',
        ),
    ]
