# Generated by Django 3.0.5 on 2020-05-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200507_0127'),
        ('posts', '0004_auto_20200506_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLike', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='content_id',
        ),
        migrations.AddField(
            model_name='content',
            name='images',
            field=models.ManyToManyField(null=True, to='posts.Photo'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Content'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.AddField(
            model_name='like',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Content'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
