# Generated by Django 3.0.5 on 2020-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200509_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.ManyToManyField(to='posts.Photo'),
        ),
    ]
