# Generated by Django 3.0.5 on 2020-05-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200513_1350'),
        ('posts', '0005_auto_20200516_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='like',
            field=models.ManyToManyField(related_name='like', through='posts.Like', to='account.User'),
        ),
    ]
