# Generated by Django 3.0.5 on 2020-05-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200516_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='isLike',
        ),
    ]
