# Generated by Django 3.0.5 on 2020-05-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeeds',
            name='Follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Followers'),
        ),
    ]
