# Generated by Django 3.0.5 on 2020-05-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200504_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='Follower',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='followers',
            field=models.ManyToManyField(related_name='user_followers', to='account.User'),
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='follows',
            field=models.ManyToManyField(related_name='user_follows', to='account.User'),
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='posts',
            field=models.ManyToManyField(to='account.Post'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
