# Generated by Django 3.0.5 on 2020-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200513_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avartar',
            field=models.URLField(blank=True),
        ),
    ]
