# Generated by Django 3.0.5 on 2020-05-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200505_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeeds',
            name='posts',
            field=models.ManyToManyField(null=True, to='account.Post'),
        ),
    ]
