# Generated by Django 3.0.5 on 2020-05-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200505_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeeds',
            name='posts',
            field=models.ManyToManyField(blank=True, to='account.Post'),
        ),
    ]
