# Generated by Django 3.0.5 on 2020-05-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200505_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='user_id',
        ),
    ]
