# Generated by Django 3.0.5 on 2020-05-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userfeeds_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeeds',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
