# Generated by Django 3.0.5 on 2020-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userfeeds_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeeds',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_followers_+', to='account.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_user_follows_+', to='account.User'),
        ),
    ]
