# Generated by Django 3.0.5 on 2020-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200505_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeeds',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to='account.User'),
        ),
        migrations.AlterField(
            model_name='userfeeds',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='account.User'),
        ),
        migrations.DeleteModel(
            name='Follow_user',
        ),
    ]
