# Generated by Django 3.0.5 on 2020-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200505_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follows',
        ),
        migrations.AddField(
            model_name='userfeeds',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to='account.User'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
