# Generated by Django 3.0.5 on 2020-05-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200505_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='userfeeds',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
